name: relative_choice
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter


  
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  riverpod: ^2.6.1
  flutter_screenutil: ^5.9.3
  delayed_tween_animation_builder: ^0.5.1
  linear_progress_bar: ^1.1.3
  get: ^4.6.6
  flutter_card_swiper: ^7.0.2
  gradient_borders: ^1.0.0
  shared_preferences: ^2.5.1
  dio: ^5.8.0+1
  device_preview: ^1.2.0
  image_picker: ^1.1.2
  percent_indicator: ^4.0.1
  auto_size_text: ^3.0.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  freezed: ^2.5.7
  riverpod_generator: ^2.6.3
  riverpod_annotation: ^2.6.1
  loading_animation_widget: ^1.3.0
 

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.9.0

flutter:

  uses-material-design: true

  assets:
    - asset/images/
  #   - images/a_dot_ham.jpeg

  
  fonts:
     - family: Montserrat
       fonts:
         - asset: assets/fonts/Montserrat-Bold.ttf
         - asset: assets/fonts/Montserrat-Regular.ttf
         - asset: assets/fonts/Montserrat-Medium.ttf
        
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
